# Generated by Django 3.2.9 on 2022-08-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=55, verbose_name="Name")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
            ],
        ),
    ]
